module main;


def main()
{
	try{
	    let a = 10;
	}
	catch a {
	    pritnln("An error occurred!");
	}
}